### PR TITLE
ci: Change Windows build target

### LINKED ISSUE #171: Use MSVC toolchain for Windows release builds
The GNU toolchain binary is extremely large (15MB) when compared to MSVC binary (which is just 4.6MB).

~Hopefully just changing matrix target in .github/workflows/release.yml from `x86_64-pc-windows-gnu` to `x86_64-pc-windows-msvc` should be enough.~

### PR DESCRIPTION
**Pull request by rashil2000**
Closes #171

### CODE REVIEW

**Comment by rashil2000** [comment]
Also, would you mind editing the current release to use the MSVC binary (linked below) instead? It was generated through the runner in my fork, you can see the run here - https://github.com/rashil2000/silicon/actions/runs/1113723609)

https://github.com/rashil2000/silicon/releases/download/v0.4.3/silicon-v0.4.3-x86_64-pc-windows-msvc.tar.gz

**Comment by rashil2000** [comment]
@Aloxaf bump?

**Comment by Aloxaf** [comment]
Thanks!

**Comment by rashil2000** [comment]
Hey @Aloxaf 
You didn't update the release binary?

**Pull request merged**
